Fix #161,#162 - Add to_names_X and from_names_X methods to EmbeddingSet
RasaHQ/whatlies pull request #164
Opened 2020-08-24 18:26 UTC by mkaze

This PR fixes #161 and #162.

2020-08-24 19:00 UTC, koaning commented on whatlies/embeddingset.py
> +        X = np.array(X)
I think we should test if `X.shape[0]` == `len(names)` here. Otherwise `zip` might cause unexpected behaviour.

2020-08-24 19:02 UTC, koaning requested changes
I think we might need to check a shape, `zip` can cause unexpected behaviour. 

```
> list(zip('abc', [1,2]))
[('a', 1), ('b', 2)]
```

2020-08-24 19:07 UTC, mkaze commented
@koaning `zip` would consume the passed iterables until either of them have no elements and hence it would stop there. But that's a good think to notify the user by raising an error. I'll work on it.

2020-08-25 06:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @TyDunn will take a look at it as soon as possible ✨

2020-08-25 07:30 UTC, koaning approved these changes

2020-08-25 07:30 UTC, koaning commented
LGTM!

2020-08-25 07:30 UTC, merged